config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :memberships
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :diplome, presence: true
  validates :age, presence: true
  validates :activity, presence: true
  validates :massif, presence: true
  validates :periode, presence: true
  validates :siret, presence: true, uniqueness: true
  validates :description, presence: true
  validates :photo, presence: true

  after_create :send_creation_confirmation_email

  private

  def send_creation_confirmation_email
    MembershipMailer.creation_confirmation(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships

  def name
    email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    # @memberships = Membership.all
    @memberships = policy_scope(Membership).order("RANDOM()")
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    authorize @membership
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    # @membership = current_user.memberships.build(membership_params)
    @membership = Membership.new(membership_params)
    @membership.user = current_user
    authorize @membership

    respond_to do |format|
      if @membership.save
        format.html { redirect_to memberships_path, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])
    @membership.update(membership_params)
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
      authorize @membership
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:first_name, :last_name, :diplome, :age, :activity, :massif, :periode, :passmorgiou, :passsormiou, :siret, :description, :photo, :photo_cache)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPPN</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body class="<%= controller_name %>-<%= action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/memberships/_card.html.erb
<div class="card">

  <div class="avatar-card">
    <%= link_to " ", membership, class: "card-link" %>
    	<%= cl_image_tag membership.photo, :width=>150, :height=>150, :crop=>"thumb", style: "border-radius: 50%;"%>
	</div>

	    <h2><%= membership.last_name.upcase %></h2>
	    <h2><%= membership.first_name.capitalize %></h2>

  <div class="card-tools">
    <% if policy(membership).update? %>
      <%= link_to edit_membership_path(membership) do %>
        <i class="fa fa-pencil-square-o picto-card" aria-hidden="true"></i>
      <% end %>
    <% end %>

    <% if policy(membership).destroy? %>
      <%= link_to membership, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash picto-card" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/memberships/_form.html.erb
<div class="container">

  <div class="form-group col-xs12 col-sm6 col-smoffset-3">
    <%= simple_form_for(@membership) do |f| %>
    <%= f.error_notification %>

      <%= f.input :last_name, label:"Nom", placeholder: "NOM", error: 'Veuillez renseigner votre nom'%>
      <%= f.input :first_name,label:"Prénom", placeholder: "Prénom", error: 'Veuillez renseigner votre prénom' %>
      <%= f.input :age, label:"Date de naissance", placeholder: "jj/mm/aaaa", error: 'Veuillez renseigner votre date de naissance' %>
      <%= f.input :diplome, label:"Diplômes", placeholder: "BE Escalade...", error: 'Veuillez renseigner au moins un diplôme' %>
      <%= f.input :activity, label:"Activités", placeholder: "Activités", error: 'Veuillez renseigner au moins une activitée' %>
      <%= f.input :massif, label:"Massif d'intervention", placeholder: "Massif d'intervention", error: "Veuillez renseignerau moins un massif d'intervention" %>
      <%= f.input :periode, label:"Période d'intervention", placeholder: "Période d'intervention", error: "Veuillez renseigner une période d'intervention" %>
      <%= f.input :passmorgiou, as: :boolean, checked_value: true, unchecked_value: false, label:"Demande de Pass pour Morgiou" %>
      <%= f.input :passsormiou, as: :boolean, checked_value: true, unchecked_value: false, label:"Demande de Pass pour Sormiou" %>
      <%= f.input :siret, label:"SIRET", placeholder: "SIRET", error: 'Veuillez renseigner votre SIRET' %>
      <%= f.input :description, label:"Description", placeholder: "Petit descriptif", error: 'Veuillez remplir un petit descriptif' %>
      <%= f.input :photo, error: 'Veuillez ajouter une photo' %>
      <%= f.input :photo_cache, as: :hidden %>

      <%= f.submit class: "btn btn-primary", value: "Soumettre les modifications" %>

    <% end %>
  </div>
</div>

app/views/memberships/edit.html.erb
<div class="class text-center">
  <h1>Editing Membership</h1>
</div>

<div class="container">
  <div class="form-group col-xs12 col-sm6 col-smoffset-3">
    <%= simple_form_for(@membership) do |f| %>
    <%= f.error_notification %>

    <%= render 'form', membership: @membership %>

    <%= link_to 'Back', memberships_path %>

    <% end %>
  </div>
</div>

app/views/memberships/index.html.erb
<div class="text-center">
  <h1>Liste des membres</h1>
  <% if policy(Membership).create? %>
        <%= link_to 'Formulaire d\'inscription', new_membership_path, class: 'btn btn-success' %>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <% @memberships.each do |membership| %>

      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= render "card", membership: membership %>
      </div>

    <% end %>
  </div>
</div>

app/views/memberships/new.html.erb
<div class="container value-prop">
  <div class="row">

      <div class="feature col-xs-12 col-sm-4">
        <h1>New Membership</h1>

        <%= render 'form', membership: @membership %>

        <%= link_to 'Back', memberships_path, class: 'btn btn-default btn-small'%>
    </div>
  </div>
</div>

app/views/memberships/show.html.erb
<div class="class text-center">
  <% content_for(:title_tag) do %>
  Read <%= @membership.last_name %> on SPPN
  <% end %>
</div>


      <div class="class text-center">
        <% if @membership.photo? %>
          <%= cl_image_tag @membership.photo, radius: 20, width: 300, height: 300, crop: :thumb %>
        <% end %>

        <h2><%= @membership.last_name.upcase %></h2>
        <h2><%= @membership.first_name.capitalize %></h2>
        <p><%= @membership.diplome %></p>
        <p><%= @membership.age %></p>
        <p><%= @membership.activity %></p>
        <p><%= @membership.massif %></p>
        <p><%= @membership.periode %></p>
        <p><%= @membership.description %></p>


        <% if policy(@membership).edit? %>
          <%= link_to 'Edit', edit_membership_path(@membership) %>
        <% end %>
        <%= link_to 'Back', memberships_path %>
      </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), crop: :fill">
  <div class="banner-content">
    <h1>Bienvenue sur le site du SPPN</h1>
    <p>Syndicat des Professionnels de Pleine Nature</p>
    <a href="memberships#index" class="btn btn-success btn-lg">Liste des Membres</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <p>Le syndicat des professionnels de pleine nature ou SPPN a pour objet la représentation ou la défense des intérêts professionnels, matériels, moraux et économiques des personnes pratiquant des activités de pleine nature en région PACA et plus particulièrement au sein du massif du parc national des calanques.
Ces activités peuvent être par exemple la randonnée pédestre, l’Escalade, la spéléologie, le VTT, Kayak, activités nautiques… sans préjudice de toute autre profession ou activité présente ou future assimilable à celle-ci et compatible avec les statuts, le cas échéant le Règlement Intérieur et la déontologie du SPPN.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <p>Dans le cadre de l’objet ci-dessus mentionné, le SPPN devra notamment:</p>
      <p>Mettre en œuvre tout moyen et créer tout service propre à assurer la liaison entre les différents statuts d’exercice et activités représentées, édicter toute règle déontologique et prendre toute décision de nature à faciliter à ses adhérents l’exercice de leur activité, le tout dans le respect de ses présents statuts, de son Règlement Intérieur et de sa Déontologie.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <p>Défendre les intérêts de ses membres tant auprès des Pouvoirs Publics français et européens qu’auprès des organismes du monde économique et social, des structures paritaires et promouvoir toute mesure de nature à favoriser l’exercice de leur profession et le développement de leur activité. Le SPPN s’interdit tout acte de commerce ainsi que toute discussion d’ordre politique ou religieux.</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= cl_image_tag("40999046-Ecologie-arbre-logo-vecteur-Banque-d_images_wmnidn.jpg") %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
      <i class="fa fa-search"></i>
      </button>
    </form> -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <!-- Notification -->
    <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <!-- <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <% end %> -->
    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle", class="avatar dropdown-toggle", id="navbar-wagon-menu", data-toggle ="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <!--
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
        -->

            <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>

            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
        </ul>
      </div>
    </div>
    <% else %>

      <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "btn btn-success btn-sml navbar-wagon-link" %>

    <!-- Login text link -->

      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "btn btn-success btn-sml navbar-wagon-link" %>

    <% end %>
    <!-- Button (call-to-action) -->
    <!-- <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>